### ISSUE TITLE
KeyError in hfstol when searching for strings in quick succession 

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#120]
```
Internal Server Error: /_search_results/ac/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/CreeDictionary/views.py", line 26, in search_results
    lemmas = Inflection.fetch_lemmas_by_user_query(query_string)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/API/models.py", line 158, in fetch_lemmas_by_user_query
    fst_analyses: Set[str] = descriptive_analyzer.feed_in_bulk_fast([user_query])[
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 130, in feed_in_bulk_fast
    return self._call_hfstol(list(strings), multi_process)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 214, in _call_hfstol
    results[original_input].add(res)
KeyError: 'a'
```

**Comment by Madoshakalaka** [comment]
the heck. I'm on it.

**Comment by eddieantonio** [comment]
Here's another example of it:

https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary/jobs/597054345#L386-L402

```
Internal Server Error: /_search_results/acâhko/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/CreeDictionary/views.py", line 26, in search_results
    lemmas = Inflection.fetch_lemmas_by_user_query(query_string)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/API/models.py", line 158, in fetch_lemmas_by_user_query
    fst_analyses: Set[str] = descriptive_analyzer.feed_in_bulk_fast([user_query])[
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 130, in feed_in_bulk_fast
    return self._call_hfstol(list(strings), multi_process)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 214, in _call_hfstol
    results[original_input].add(res)
KeyError: 'acâhkos'
```

It's easily triggered by the integration tests.

**Comment by eddieantonio** [comment]
![Screen Shot 2019-10-15 at 4 06 47 PM](https://user-images.githubusercontent.com/2294397/66873498-d709f480-ef65-11e9-9ebc-185c0b8e69aa.png)


https://www.youtube.com/watch?v=_asNhzXq72w

**Comment by eddieantonio** [comment]
I think I have an idea for a reproducible test case.

Look-up a word with A LOT of possible analyses, e.g., "ôma":

```
$ pipenv run analyze
Loading .env environment variables…
!! Warning: file contains more than one transducer          !!
!! This is currently not handled - using only the first one !!
ôma
ôma	ôma+Ipc+Foc
ôma	ôma+Pron+Dem+Prox+IN+Sg
ôma	ôma+Pron+Def+Prox+IN+Sg
```

Then try to look up something else.

**Comment by Madoshakalaka** [comment]
fully fixed
https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary/builds/600235228

**Comment by eddieantonio** [comment]
@Madoshakalaka, I've got bad news for you:

```
Internal Server Error: /_search_results/acâhk/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/CreeDictionary/views.py", line 31, in search_results
    lemmas = Inflection.fetch_lemmas_by_user_query(query_string)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/API/models.py", line 155, in fetch_lemmas_by_user_query
    fst_analyses: Set[str] = descriptive_analyzer.feed_in_bulk_fast([user_query])[
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 131, in feed_in_bulk_fast
    return self._call_hfstol(list(strings), multi_process)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 220, in _call_hfstol
    results[original_input].add(res)
KeyError: 'acâhkos'
[22/Oct/2019 17:05:10] "GET /_search_results/ac%C3%A2hk/ HTTP/1.1" 500 115192
      1) should search for an exact lemma
[22/Oct/2019 17:05:14] "GET /search/amisk HTTP/1.1" 301 0
[22/Oct/2019 17:05:14] "GET /search/amisk/ HTTP/1.1" 200 7906
[22/Oct/2019 17:05:14] "GET /jsreverse/ HTTP/1.1" 200 4214
[22/Oct/2019 17:05:14] "GET /static/CreeDictionary/js/index.js HTTP/1.1" 304 0
Internal Server Error: /_search_results/acâhkos/
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/CreeDictionary/views.py", line 31, in search_results
    lemmas = Inflection.fetch_lemmas_by_user_query(query_string)
  File "/home/travis/build/UAlbertaALTLab/cree-intelligent-dictionary/CreeDictionary/API/models.py", line 155, in fetch_lemmas_by_user_query
    fst_analyses: Set[str] = descriptive_analyzer.feed_in_bulk_fast([user_query])[
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 131, in feed_in_bulk_fast
    return self._call_hfstol(list(strings), multi_process)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/hfstol/main.py", line 220, in _call_hfstol
    results[original_input].add(res)
KeyError: 'amisk'
```

https://travis-ci.org/UAlbertaALTLab/cree-intelligent-dictionary/jobs/601387324#L379-L420

---

What is the _underlying_ bug here? What _actually_ is going wrong?

**Comment by eddieantonio** [comment]
I disabled the HFSTOL descriptive analyzer so that we have less flakey builds as of 74a6fb0. Since this bug keeps popping back up, I think we should put it on the back-burner, since the slower implementation still works -- it's just slower 🤷‍♂ .

I've set this as a "future" task, since all the tests pass, and the site work without using hfstol.

**Comment by Madoshakalaka** [comment]
very depressing. But sure

**Comment by eddieantonio** [comment]
I'm marking this as `wontfix`. Eventually, we'll have to implement an hfstol evaluator that is stable, can be installed without external dependencies via pypi, and does not have weird concurrency bugs!
