### ISSUE TITLE
bug: min() arg is an empty sequence (search.py goof)

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/cree-intelligent-dictionary#693]
500 error in logs:

```
itwewina_1  | [pid: 15|app: 0|req: 110/599] 192.168.190.12 () {44 vars in 850 bytes} [Fri Mar 12 22:58:26 2021] GET /_search_results/bo/ => generated 162 bytes in 30 msecs (HTTP/1.0 200) 11 headers in 409 bytes (1 switches on core 0)
itwewina_1  | can not generate standardized form for analysis pôti+Ipc
itwewina_1  | Internal Server Error: /_search_results/bod/
itwewina_1  | Traceback (most recent call last):
itwewina_1  |   File "/app/.venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
itwewina_1  |     response = get_response(request)
itwewina_1  |   File "/app/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
itwewina_1  |     response = self.process_exception_by_middleware(e, request)
itwewina_1  |   File "/app/.venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
itwewina_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
itwewina_1  |   File "./CreeDictionary/views.py", line 120, in search_results
itwewina_1  |     results = Wordform.search_with_affixes(
itwewina_1  |   File "./API/models.py", line 266, in search_with_affixes
itwewina_1  |     return search.perform(include_auto_definitions=include_auto_definitions)
itwewina_1  |   File "./API/search.py", line 287, in perform
itwewina_1  |     res = self.fetch_bilingual_results()
itwewina_1  |   File "./API/search.py", line 389, in fetch_bilingual_results
itwewina_1  |     return fetch_cree_and_english_results(self.cleaned_query, affix_search=True)
itwewina_1  |   File "./API/search.py", line 498, in fetch_cree_and_english_results
itwewina_1  |     _fetch_results(user_query, cree_results, english_results)
itwewina_1  |   File "./API/search.py", line 552, in _fetch_results
itwewina_1  |     normatized_user_query = min(
itwewina_1  | ValueError: min() arg is an empty sequence
itwewina_1  | [pid: 14|app: 0|req: 150/600] 192.168.190.12 () {44 vars in 853 bytes} [Fri Mar 12 22:58:27 2021] GET /_search_results/bod/ => generated 27 bytes in 85 msecs (HTTP/1.0 500) 11 headers
```

**Comment by eddieantonio** [comment]
Update: this can be reproduced by searching for **bod**.

**Comment by fbanados** [comment]
A new test is required to avoid a regression of this failure.  New FSTs generate `pôti` for the non-standard form `pôti+Ipc`, so tests that were expecting a failure on this input now succeed.  @aarppe Is this expected behavior for the FST?  If so, we need a new example of a search accepted by the descriptive analyzer generating an analysis which cannot be then generated by the strict generator.  However, it may also be the case that this should never happen once the FSTs are generated correctly?
