### ISSUE TITLE
Site crashes when searching for ‘ôhi’

### ISSUE THREAD

**Issue by andrewdotn** [UAlbertaALTLab/cree-intelligent-dictionary#930]

**Comment by andrewdotn** [comment]
nêhi as well

**Comment by eddieantonio** [comment]
I wonder if this is related to the fact that _nêki cannot be searched in the production database_! Is there something weird happening with the demonstrative pronouns?

**Comment by eddieantonio** [comment]
Traceback for searching for _nêhi_:

```
Traceback (most recent call last):
  File "/Users/santoseadmin/.local/share/virtualenvs/cree-intelligent-dictionary-QnVLIb_Q/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/santoseadmin/.local/share/virtualenvs/cree-intelligent-dictionary-QnVLIb_Q/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/santoseadmin/Work/cree-intelligent-dictionary/src/CreeDictionary/CreeDictionary/views.py", line 104, in index
    search_run = search_with_affixes(
  File "/Users/santoseadmin/Work/cree-intelligent-dictionary/src/CreeDictionary/API/search/__init__.py", line 13, in search_with_affixes
    return search(query=query, include_auto_definitions=include_auto_definitions)
  File "/Users/santoseadmin/Work/cree-intelligent-dictionary/src/CreeDictionary/API/search/runner.py", line 45, in search
    fetch_results(search_run)
  File "/Users/santoseadmin/Work/cree-intelligent-dictionary/src/CreeDictionary/API/search/lookup.py", line 74, in fetch_results
    possible_lemma_wordforms = best_lemma_matches(
  File "/Users/santoseadmin/Work/cree-intelligent-dictionary/src/CreeDictionary/API/search/lookup.py", line 121, in best_lemma_matches
    max_tag_intersection_count = max(

Exception Type: ValueError at /search
Exception Value: max() arg is an empty sequence
```

Statement of the crash:

```python
    max_tag_intersection_count = max(
        analysis.tag_intersection_count(lwf.analysis)
        for lwf in possible_lemmas
        if lwf.analysis
    )
```

Significant variables:

```python
>>> possible_lemmas
[<Wordform: nêhi None>, <Wordform: nêhi None>]
>>> [lwf for lwf in possible_lemmas if lwf.analysis]
[]
```

**Comment by eddieantonio** [comment]
Why would the database entries for “nêhi” and “ôhi” not contain an analysis in the database? They have analyses to spare:

https://itwewina.altlab.app/admin/fst-tool?text=%C3%B4hi

```
strict_analyzer
ôhi+Pron+Dem+Prox+I+Pl
ôhi+Pron+Dem+Prox+A+Obv
ôhi+Pron+Def+Prox+I+Pl
```

https://itwewina.altlab.app/admin/fst-tool?text=n%C3%AAhi

```
nêhi+Pron+Dem+Dist+I+Pl
nêhi+Pron+Dem+Dist+A+Obv
nêhi+Pron+Def+Dist+I+Pl
```
